#!/bin/sh

case $1 in
  "m:seed")
    php spark db:seed Main
    ;;
  "m:run")
    php spark migrate
    ;;
  "m:undo")
    php spark migrate:rollback
    ;;
  "m:stats")
    php spark migrate:status
    ;;
esac
